name: Pipeline

on:
  push:
    branches: ['main']
    
  watch:
    types: [started]

jobs:
  deploy:
    name: Build && Push image to docker hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}
    
      - name: Setup Docker Buildx
        uses: docker/setup-qemu-action@v3
    
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      
      - name: Build And Push Api
        id: build-push-api
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          file: Dockerfile
          tags: vyronfiee/pnpm:latest